//tslint:disable: no-string-literal
import { readFileSync, writeFileSync, existsSync } from 'fs';
import { prompt as ask } from 'inquirer';
import { safeDump } from 'js-yaml';
import { logInfo } from '../utils';

const configFilesPath = `${__dirname}/resources/config`;

const dockerFilesPath = `${__dirname}/resources/docker`;

const encoding = "utf8";
const mongoDB = "MongoDB";
const sqlite3 = "sqlite3";
const postgreSQL = "PostgreSQL";
/**
 * Different database choices
 */
const getConfig = (database: string) => {
  if (database === postgreSQL) {
    return [readFileSync(`${configFilesPath}/postgres.json`, encoding), readFileSync(`${dockerFilesPath}/postgres.yml`, 'utf8')];
  } else if (database === mongoDB) {
    return ["", readFileSync(`${dockerFilesPath}/mongodb.yml`, encoding)];
  } else if (database === sqlite3) {
    return [readFileSync(`${configFilesPath}/sqlite3.json`, encoding), undefined];
  } else {
    return undefined;
  }
}

const databases = [
  postgreSQL,
  mongoDB,
  sqlite3
];

export const chooseDatabase = async (): Promise<string> => {
  const { database } = await ask({
    type: 'list',
    name: 'database',
    message: 'Choose your database',
    choices: databases
  });

  return database;
}

export const askForClient = async (): Promise<boolean> => {
  const { client } = await ask({
    type: 'confirm',
    name: 'client',
    message: 'Do you want to generate client-side queries?'
  });

  return client;
};

/**
 * Create config file with db info
 */
export const createConfig = async (database: string, client: boolean) => {
  const configPath = `${process.cwd()}/.graphqlrc.yml`;

  if (existsSync(configPath)) {
    logInfo("Graphback config already exist in following location and it cannot be overwritten");
  }

  const dockerComposePath = `${process.cwd()}/docker-compose.yml`;
  const [_, dockerCompose] = getConfig(database);

  const graphqlConfig = {
    schema: './src/schema/*.graphql',
    documents: './client/src/graphql/**/*.graphql',
    extensions: {
      graphback: {
        "model": "./model/**/*.graphql",
        "crud": {
          "create": true,
          "update": true,
          "findOne": true,
          "find": true,
          "delete": false,
          "subCreate": false,
          "subUpdate": false,
          "subDelete": false
        },
        "plugins": {
          "graphback-schema": {
            "format": "graphql",
            "outputPath": "./src/schema"
          }
        }
      }
    }
  };

  if (client) {
    //Add client extension
    graphqlConfig.extensions.graphback.plugins["graphback-client"] = {
      "format": "graphql",
      "outputPath": "./client/src/graphql"
    };
  }

  if (dockerCompose) {
    if (existsSync(dockerComposePath)) {
      logInfo(`${dockerComposePath} file already exists. No need to generate one, if you do not have a "${database}" database entry in the existing file, you can add it with the following content:
       """
       ${dockerCompose} 
       """`);
    } else {
      writeFileSync(dockerComposePath, dockerCompose);
    }
  }

  const finalConfig = `## GraphQL Config Generated by Graphback
## Please review configuration and adjust it for your own project
${safeDump(graphqlConfig)}
`;

  writeFileSync(configPath, finalConfig);
};
