/*
 * File generated by Graphback CRUD resolver plugin.
 * Content will be overwritten by Graphback generator.
 * To change implementation please disable generator options and supply your own implementation
 * outside generated file.
 */

export default {
  Note: {
    comments: (parent, args, context) => {
      return context.Comment.batchLoadData("noteCommentId", parent.id, context)
    },
  },

  Comment: {
    noteComment: (parent, args, context) => {
      return context.Note.findBy({ id: parent.noteCommentId }).then(
        (results) => results[0]
      )
    },
  },

  Query: {
    findNotes: (parent, args, context) => {
      const { filter, ...page } = args
      return context.Note.findBy(filter, page)
    },
    findAllNotes: (parent, args, context) => {
      return context.Note.findAll(args)
    },
    findComments: (parent, args, context) => {
      const { filter, ...page } = args
      return context.Comment.findBy(filter, page)
    },
    findAllComments: (parent, args, context) => {
      return context.Comment.findAll(args)
    },
  },

  Mutation: {
    createNote: (parent, args, context) => {
      return context.Note.create(args.data, context)
    },
    updateNote: (parent, args, context) => {
      return context.Note.update(args.data, context)
    },
    createComment: (parent, args, context) => {
      return context.Comment.create(args.data, context)
    },
    updateComment: (parent, args, context) => {
      return context.Comment.update(args.data, context)
    },
  },
}
