/**
 * File generated by Graphback CRUD resolver plugin.
 * Content will be overwritten by Graphback generator.
 * To change implementation please disable generator options and supply your own implementation
 * outside generated file.
 */

export default {
  Query: {
    findTodos: (parent, args, context) => {
      return context.Todo.findBy(args.fields)
    },
    findAllTodos: (parent, args, context) => {
      return context.Todo.findAll()
    }
  },

  Mutation: {
    createTodo: (parent, args, context) => {
      return context.Todo.create(args.input, context)
    },
    updateTodo: (parent, args, context) => {
      return context.Todo.update(args.input, context)
    },
    deleteTodo: (parent, args, context) => {
      return context.Todo.delete(args.input, context)
    }
  },

  Subscription: {
    newTodo: {
      subscribe: (parent, args, context) => {
        return context.Todo.subscribeToCreate(args, context)
      }
    },
    updatedTodo: {
      subscribe: (parent, args, context) => {
        return context.Todo.subscribeToUpdate(args, context)
      }
    },
    deletedTodo: {
      subscribe: (parent, args, context) => {
        return context.Todo.subscribeToDelete(args, context)
      }
    }
  }
}
