
/**
 * Definition of the runtime resolvers generated by `LayeredRuntimeResolverGen`
 */
export interface RuntimeResolversDefinition {
    schema: string

    /**
     * Resolvers in Apollo GraphQL format
     */
    // tslint:disable-next-line: no-any
    resolvers: any;
}