
/**
 * Definition of the runtime resolvers generated by `LayeredRuntimeResolverGen`
 */
export interface RuntimeResolversDefinition {
    
    /**
     * Generated schema
     */
    schema: string

    /**
     * Resolvers in Apollo GraphQL format
     */
    resolvers: Object;
}