schema: ./src/schema/*.graphql
extensions:
  # Graphback configuration
  graphback:
    ##  Input schema
    model: ./model/**/*.graphql
    ## Global configuration for CRUD generator
    crud:
      create: true
      update: true
      findAll: true
      find: true
      delete: true
      subCreate: true
      subUpdate: true
      subDelete: true
    ## Codegen plugins
    plugins:
        graphback-schema:
          format: 'graphql'
          outputPath: ./server/src/schema
        graphback-resolvers:
          format: ts
          outputPath: ./server/src/resolvers
    ## Knex DB Migration config
  dbmigrations:
    ## See knex.js for db specific config format
    client: pg
    connection:
      user: postgresql
      password: postgres
      database: users
      host: localhost
      port: 55432
