version: 2
jobs:
  build:
    working_directory: ~/graphback
    docker:
      # Node 8 LTS
      - image: circleci/node:lts
        environment:
          NODE_OPTIONS: --max_old_space_size=4096
      - image: circleci/postgres:latest
        environment:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgresql
          POSTGRES_DB: users
      - image: circleci/mongo:latest
        environment:
          MONGO_INITDB_DATABASE: users
          MONGO_INITDB_ROOT_USERNAME: mongodb
          MONGO_INITDB_ROOT_PASSWORD: mongo
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-dependencies
          command: yarn
      - run:
          name: install-package-dependencies
          command: yarn bootstrap
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: run lint
          command: yarn lint
      - run:
          name: build-packages
          command: yarn build
      - run:
          name: test
          command: yarn test
      - run:
          name: run integration tests
          command: yarn test:integration
  npm_publish:
    working_directory: ~/aerogear/graphback
    docker:
      # Node 8 LTS
      - image: circleci/node:lts
    steps:
      - checkout
        # Allows us to authenticate with the npm registry
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run: CI=true npm run release:prep
      - run: TAG=$CIRCLE_TAG npm run publish

workflows:
  version: 2
  build_and_release:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - npm_publish:
          requires:
            - build
          filters:
            tags:
              only: /.*/ # allow anything because tag syntax is validated as part of validate-release.sh
            branches:
              ignore: /.*/
