/**
 * File generated by Graphback CRUD resolver plugin.
 * Content will be overwritten by Graphback generator.
 * To change implementation please disable generator options and supply your own implementation
 * outside generated file.
 */

export default {
  Query: {
    findNotes: (parent, args, context) => {
      return context.Note.findBy(args.fields)
    },
    findAllNotes: (parent, args, context) => {
      return context.Note.findAll()
    },
    findComments: (parent, args, context) => {
      return context.Comment.findBy(args.fields)
    },
    findAllComments: (parent, args, context) => {
      return context.Comment.findAll()
    }
  },

  Mutation: {
    createNote: (parent, args, context) => {
      return context.Note.create(args.input, context)
    },
    updateNote: (parent, args, context) => {
      return context.Note.update(args.input, context)
    },
    createComment: (parent, args, context) => {
      return context.Comment.create(args.input, context)
    },
    updateComment: (parent, args, context) => {
      return context.Comment.update(args.input, context)
    }
  }
}
