schema:
    ./server/src/schema/index.ts:
        require: ts-node/register
documents: './client/src/graphql/**/*.ts'
extensions:
    generate:
        db:
            dbConfig:
                user: postgresql
                password: postgres
                database: users
                host: localhost
                port: 55432
            database: pg
        graphqlCRUD:
            create: true
            update: true
            findAll: true
            find: true
            delete: false
            subCreate: false
            subUpdate: false
            subDelete: false
            disableGen: false
        folders:
            model: ./model
            resolvers: ./server/src/resolvers
            schema: ./server/src/schema
            client: ./client/src/graphql
    codegen:
        ./server/src/generated-types.ts:
            plugins:
                - typescript
                - typescript-resolvers
        ./client/src/generated-types.tsx:
            plugins:
                - typescript
                - typescript-operations
                - typescript-react-apollo
            config:
                withComponent: false
                withHOC: false
                withHooks: true
