
/**
 * Interface represents graphback models that are generated by default resolver generator
 */
export interface GraphbackPubSubModel {
    name: string,
    pubSub: PubSubConfig
}

/**
 * Configuration for the publish subscribe model
 */
export interface PubSubConfig {
    publishCreate?: boolean;
    publishUpdate?: boolean;
    publishDelete?: boolean;
}

