schema: ./src/schema/*.graphql
extensions:
  # Graphback configuration
  graphback:
    ##  Input schema
    model: ./model/**/*.graphql
    ## Global configuration for CRUD generator
    crud:
      create: true
      update: true
      findAll: true
      find: true
      delete: true
      subCreate: true
      subUpdate: true
      subDelete: true
    ## Codegen plugins
    plugins:
        graphback-schema:
          format: 'graphql'
          outputPath: ./server/src/schema
        graphback-client:
          format: 'graphql'
          outputPath: ./client/src/graphql
 