schema: './src/schema.graphql'
documents: ./client/src/graphql/**/*.graphql
extensions:
  graphback:
    model: ./model/datamodel.graphql
    plugins:
      graphback-client:
        format: 'ts'
        outputFile: ./client/src/graphql/graphback.ts
