version: '3'

services:
  postgres:
    image: postgres:15.2
    ports:
      - "55432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgresql
      POSTGRES_DB: users
